In [44]:
import pandas as pd
import numpy as np
from sklearn import tree
from sklearn.cross_validation import train_test_split

In [45]:
default = pd.read_csv("Default.csv")
default.head()


Unnamed: 0 default student      balance        income
0           1      No      No   729.526495  44361.625074
1           2      No     Yes   817.180407  12106.134700
2           3      No      No  1073.549164  31767.138947
3           4      No      No   529.250605  35704.493935
4           5      No      No   785.655883  38463.495879

In [4]:
default['default'].value_counts()

No     9667
Yes     333
Name: default, dtype: int64

In [40]:
default['default'] = default['default'].apply(lambda x: 1 if x == 'Yes' else 0)
default['student']=default['student'].apply(lambda x: 1 if x=='Yes' else 0)

In [8]:
sam=np.random.randint(3,size=10)
colors = ['red','blue','green']
listcol =[colors[i] for i in sam]
df =pd.Series(listcol)
print df.head()

0     blue
1      red
2      red
3     blue
4    green
dtype: object


In [9]:
pd.get_dummies(df)

blue  green  red
0     1      0    0
1     0      0    1
2     0      0    1
3     1      0    0
4     0      1    0
5     1      0    0
6     0      0    1
7     0      1    0
8     1      0    0
9     1      0    0

In [11]:
pd.get_dummies(df,prefix = 'red or').drop(labels='red or_red',axis=1)

red or_blue  red or_green
0            1             0
1            0             0
2            0             0
3            1             0
4            0             1
5            1             0
6            0             0
7            0             1
8            1             0
9            1             0

In [41]:
X=default[['balance','income','student']]
Y=default['default']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)
clf = tree.DecisionTreeClassifier(criterion='entropy',class_weight='balanced')
clf = clf.fit(X_train, Y_train)

In [42]:
clf.feature_importances_

array([ 0.82374697,  0.17398375,  0.00226928])

In [43]:
clf.classes_

array([0, 1])

In [26]:
clf.tree_.max_depth

28

In [27]:
clf.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0])

In [33]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, clf.predict(X_test))  # if the classes are 1,0, do not use the labels

array([[2830,   76],
       [  66,   28]])

In [36]:
from sklearn.ensemble import RandomForestClassifier
clf_ran = RandomForestClassifier(n_estimators=1000,class_weight="balanced")
clf_ran = clf_ran.fit(X_train,Y_train)

In [37]:
confusion_matrix(Y_test, clf_ran.predict(X_test))

array([[2878,   28],
       [  64,   30]])